name: verite-drupal
recipe: drupal8
config:
  framework: drupal8
  webroot: .
  xdebug: true
services:
  node-cli:
    type: 'node:4.8'
    globals:
      gulp-cli: latest
    extras:
      - cd $LANDO_MOUNT && npm install
tooling:
  npm:
    service: node-cli
  node:
    service: node-cli
  gulp:
    service: node-cli
